import React from 'react'

function SpreadBar({ lowTarget, highTarget }) {
  const range = highTarget - lowTarget
  const pct = ((range / lowTarget) * 100).toFixed(0)
  return (
    <div className="flex flex-col gap-1 min-w-[220px]">
      <div className="flex items-center justify-between text-[10.5px] text-slate-500 uppercase tracking-widest">
        <span>Low</span>
        <span className="text-amber-400">Spread {pct}%</span>
        <span>High</span>
      </div>
      <div className="h-1.5 rounded-full bg-gradient-to-r from-rose-500/60 via-slate-500/30 to-emerald-500/60"/>
      <div className="flex items-center justify-between text-[11.5px] num">
        <span className="text-rose-400">${lowTarget.toLocaleString()}</span>
        <span className="text-emerald-400">${highTarget.toLocaleString()}</span>
      </div>
    </div>
  )
}

function brokerName(brokers, id) {
  return brokers.find((b) => b.id === id)?.shortName || id.toUpperCase()
}

function DivergenceCard({ d, brokers }) {
  return (
    <article className="panel p-5 flex flex-col gap-4">
      <header className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <div className="section-title">Divergence · {d.ticker}</div>
          <h3 className="text-slate-100 text-[15px] font-semibold mt-1">{d.title}</h3>
          <div className="text-[11.5px] text-slate-400 mt-1">
            Low: <span className="text-rose-400">{brokerName(brokers, d.spread.lowBroker)}</span>
            <span className="mx-1 text-slate-600">·</span>
            High: <span className="text-emerald-400">{brokerName(brokers, d.spread.highBroker)}</span>
          </div>
        </div>
        <SpreadBar lowTarget={d.spread.lowTarget} highTarget={d.spread.highTarget}/>
      </header>

      <div>
        <div className="section-title mb-2">Conflicting assumptions</div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
          {d.conflicts.map((c, idx) => (
            <div key={idx} className="rounded border border-white/5 bg-white/[0.02] p-3 flex flex-col gap-2">
              <div className="text-[11px] uppercase tracking-widest text-slate-400">{c.topic}</div>
              <div className="flex flex-col gap-1">
                <div className="flex gap-2 text-[12px]">
                  <span className="chip border border-emerald-500/30 text-emerald-400 shrink-0">Bull</span>
                  <span className="text-slate-200 leading-snug">{c.bull}</span>
                </div>
                <div className="flex gap-2 text-[12px]">
                  <span className="chip border border-rose-500/30 text-rose-400 shrink-0">Bear</span>
                  <span className="text-slate-200 leading-snug">{c.bear}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="rounded border border-dashed border-accent/30 bg-accent/[0.04] p-3">
        <div className="flex items-center gap-2 mb-1">
          <span className="chip border border-accent/40 text-accent">AI · Conclusion</span>
          <span className="text-[10.5px] text-slate-500 uppercase tracking-widest">Placeholder · will be generated by model</span>
        </div>
        <p className="text-[12.5px] text-slate-300 leading-relaxed">{d.aiConclusion}</p>
        <div className="flex items-center gap-2 mt-2">
          <button className="chip border border-white/10 text-slate-300 hover:text-slate-100">Trigger synthesis</button>
          <button className="chip border border-white/10 text-slate-300 hover:text-slate-100">Attach to note</button>
        </div>
      </div>
    </article>
  )
}

export default function Divergence({ divergences, brokers }) {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-end justify-between flex-wrap gap-3">
        <div>
          <h2 className="text-slate-100 font-semibold text-base">Divergence / ARB Closure</h2>
          <p className="text-slate-400 text-[12px]">Names where the Street materially disagrees. Each case surfaces the conflicting assumptions driving the spread — with an AI-generated conclusion slot.</p>
        </div>
        <div className="flex items-center gap-2 text-[11px]">
          <span className="section-title">Min spread</span>
          <select className="bg-white/[0.04] border border-white/5 rounded px-2 py-1 text-slate-200 text-[11px] focus:outline-none focus:border-accent/40">
            <option>25%</option><option>40%</option><option>60%</option>
          </select>
        </div>
      </div>

      <div className="grid grid-cols-1 2xl:grid-cols-2 gap-3">
        {divergences.map((d) => <DivergenceCard key={d.id} d={d} brokers={brokers}/>)}
      </div>
    </div>
  )
}
