import type { Broker } from '../domain'
import { asBrokerId } from '../lib/ids'

// Global broker catalog — top Indian institutional equity research houses.
// Per-org enablement lives on Organization.enabledBrokerIds. `senderDomains`
// is what the ingestion filter matches on when it admits inbound forwarded
// mail; `researchAliases` helps de-duplicate the same house when it forwards
// from multiple internal distribution groups.
export const brokers: readonly Broker[] = [
  {
    id: asBrokerId('brk_kotak'),
    name: 'Kotak Institutional Equities',
    shortName: 'Kotak',
    senderDomains: ['kotak.com', 'kotaksecurities.com'],
    researchAliases: ['Kotak Institutional Equities Research', 'KIE', 'Morning Insight', 'India Daily'],
    coverageTags: ['India Large Cap', 'BFSI', 'IT Services'],
    brandColor: '#d4af37',
    website: 'https://www.kotak.com',
  },
  {
    id: asBrokerId('brk_mosl'),
    name: 'Motilal Oswal',
    shortName: 'MOSL',
    senderDomains: ['motilaloswal.com'],
    researchAliases: ['Motilal Oswal Institutional Equities', 'MOFSL Research'],
    coverageTags: ['India Large Cap', 'Midcap'],
    brandColor: '#60a5fa',
    website: 'https://www.motilaloswal.com',
  },
  {
    id: asBrokerId('brk_icici'),
    name: 'ICICI Securities',
    shortName: 'I-Sec',
    senderDomains: ['icicisecurities.com', 'icici.com'],
    researchAliases: ['ICICI Securities Research', 'I-Sec'],
    coverageTags: ['India Large Cap', 'Auto', 'Consumer'],
    brandColor: '#34d399',
    website: 'https://www.icicisecurities.com',
  },
  {
    id: asBrokerId('brk_hdfc'),
    name: 'HDFC Securities',
    shortName: 'HDFC',
    senderDomains: ['hdfcsec.com', 'hdfcsecurities.com'],
    researchAliases: ['HDFC Securities Institutional Research'],
    coverageTags: ['India Large Cap', 'Auto', 'Energy'],
    brandColor: '#f87171',
    website: 'https://www.hdfcsec.com',
  },
  {
    id: asBrokerId('brk_axis'),
    name: 'Axis Capital',
    shortName: 'Axis',
    senderDomains: ['axiscap.in', 'axiscapital.in'],
    researchAliases: ['Axis Capital Institutional Research'],
    coverageTags: ['India Large Cap', 'Banks', 'Pharma'],
    brandColor: '#a78bfa',
    website: 'https://www.axiscapital.co.in',
  },
  {
    id: asBrokerId('brk_nuvama'),
    name: 'Nuvama Institutional Equities',
    shortName: 'Nuvama',
    senderDomains: ['nuvama.com', 'edelweiss.in'],
    researchAliases: ['Nuvama Institutional Equities', 'Edelweiss Securities Research'],
    coverageTags: ['India Large Cap', 'BFSI', 'IT Services'],
    brandColor: '#f472b6',
    website: 'https://www.nuvama.com',
  },
  {
    id: asBrokerId('brk_ambit'),
    name: 'Ambit Capital',
    shortName: 'Ambit',
    senderDomains: ['ambit.co'],
    researchAliases: ['Ambit Capital Institutional Research', 'Ambit'],
    coverageTags: ['India Large Cap', 'Midcap', 'Thematic'],
    brandColor: '#22d3ee',
    website: 'https://www.ambit.co',
  },
  {
    id: asBrokerId('brk_jmfin'),
    name: 'JM Financial Institutional Securities',
    shortName: 'JM Fin',
    senderDomains: ['jmfl.com', 'jmfinancial.in'],
    researchAliases: ['JM Financial Research'],
    coverageTags: ['India Large Cap', 'Energy'],
    brandColor: '#fb7185',
    website: 'https://www.jmfl.com',
  },
  {
    id: asBrokerId('brk_iifl'),
    name: 'IIFL Securities',
    shortName: 'IIFL',
    // iiflcap.com is the IIFL institutional-research delivery domain seen on
    // real inbound mail (e.g. joseph.george@iiflcap.com); iifl.com and
    // iiflsecurities.com are the customer-facing surfaces.
    senderDomains: ['iiflcap.com', 'iifl.com', 'iiflsecurities.com'],
    researchAliases: ['IIFL Institutional Equities Research'],
    coverageTags: ['India Large Cap', 'Consumer'],
    brandColor: '#fbbf24',
    website: 'https://www.iifl.com',
  },
  {
    id: asBrokerId('brk_plilladher'),
    name: 'Prabhudas Lilladher',
    shortName: 'PL',
    senderDomains: ['plindia.com'],
    researchAliases: ['Prabhudas Lilladher Institutional Research', 'PL Research'],
    coverageTags: ['India Large Cap', 'Banks'],
    brandColor: '#4ade80',
    website: 'https://www.plindia.com',
  },
  {
    id: asBrokerId('brk_investec'),
    name: 'Investec',
    shortName: 'Investec',
    senderDomains: ['investec.com', 'investec.co.za', 'investec.co.uk'],
    researchAliases: ['Investec Securities', 'Investec Bank', 'Investec Capital Services'],
    coverageTags: ['India Mid Cap', 'Consumer', 'Global'],
    brandColor: '#38bdf8',
    website: 'https://www.investec.com',
  },
  {
    id: asBrokerId('brk_choice'),
    name: 'Choice Institutional Equities',
    shortName: 'Choice',
    senderDomains: ['choiceindia.com', 'choiceinstitutionalresearch.com'],
    researchAliases: ['Choice Equity', 'Choice Institutional Research', 'Choice Broking'],
    coverageTags: ['India Mid Cap', 'Small Cap'],
    brandColor: '#818cf8',
    website: 'https://www.choiceindia.com',
  },
  {
    id: asBrokerId('brk_gs'),
    name: 'Goldman Sachs',
    shortName: 'GS',
    senderDomains: ['gs.com', 'goldmansachs.com'],
    researchAliases: ['Goldman Sachs Global Investment Research', 'GS Research'],
    coverageTags: ['Global', 'India Large Cap'],
    brandColor: '#6699cc',
    website: 'https://www.goldmansachs.com',
  },
  {
    id: asBrokerId('brk_ms'),
    name: 'Morgan Stanley',
    shortName: 'MS',
    senderDomains: ['morganstanley.com'],
    researchAliases: ['Morgan Stanley Research'],
    coverageTags: ['Global', 'India Large Cap'],
    brandColor: '#2dd4bf',
    website: 'https://www.morganstanley.com',
  },
  {
    id: asBrokerId('brk_jpm'),
    name: 'J.P. Morgan',
    shortName: 'JPM',
    senderDomains: ['jpmorgan.com'],
    researchAliases: ['JPMorgan', 'JP Morgan', 'J.P. Morgan Research'],
    coverageTags: ['Global', 'India Large Cap'],
    brandColor: '#c084fc',
    website: 'https://www.jpmorgan.com',
  },
  {
    id: asBrokerId('brk_ubs'),
    name: 'UBS',
    shortName: 'UBS',
    senderDomains: ['ubs.com'],
    researchAliases: ['UBS Securities', 'UBS Global Research'],
    coverageTags: ['Global', 'India Large Cap'],
    brandColor: '#fb923c',
    website: 'https://www.ubs.com',
  },
  {
    id: asBrokerId('brk_jefferies'),
    name: 'Jefferies',
    shortName: 'Jefferies',
    senderDomains: ['jefferies.com'],
    researchAliases: ['Jefferies Equity Research'],
    coverageTags: ['Global', 'India Large Cap'],
    brandColor: '#f59e0b',
    website: 'https://www.jefferies.com',
  },
  {
    id: asBrokerId('brk_bofa'),
    name: 'BofA Securities',
    shortName: 'BofA',
    senderDomains: ['bofa.com', 'bankofamerica.com', 'baml.com'],
    researchAliases: ['Bank of America', 'BofA Global Research', 'Merrill Lynch'],
    coverageTags: ['Global', 'India Large Cap'],
    brandColor: '#e11d48',
    website: 'https://www.bofaml.com',
  },
  {
    id: asBrokerId('brk_citi'),
    name: 'Citi',
    shortName: 'Citi',
    senderDomains: ['citi.com'],
    researchAliases: ['Citigroup', 'Citi Research'],
    coverageTags: ['Global', 'India Large Cap'],
    brandColor: '#0ea5e9',
    website: 'https://www.citigroup.com',
  },
  {
    id: asBrokerId('brk_nomura'),
    name: 'Nomura',
    shortName: 'Nomura',
    senderDomains: ['nomura.com'],
    researchAliases: ['Nomura Research', 'Nomura Securities'],
    coverageTags: ['Global', 'India Large Cap'],
    brandColor: '#ef4444',
    website: 'https://www.nomura.com',
  },
]
